<a href="https://colab.research.google.com/github/sumantsharma16/PythonTutorial/blob/main/Complete_Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Arrays:

Advantages of Numpy Arrays:

1. Allows several Mathematical Operattions
2. Faster operations

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0011071309999994838


In [4]:
 np_array = np.array([i for i in range(10000)])

 start_time = process_time()

 np_array += 5

 end_time = process_time()

 print(end_time - start_time)

0.0016928380000003074


Numpy Arrays

In [5]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape

(4,)

In [10]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [12]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial Placeholder in numpy arrays

In [13]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
# create an identy matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
# create a numpy array with radom values
b = np.random.random((3,4))
print(b)

[[0.59032582 0.76055807 0.68213344 0.94866086]
 [0.42096969 0.72884154 0.2226323  0.67158611]
 [0.34073546 0.07897158 0.26010826 0.86154026]]


In [20]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[35 32 56 80 92]
 [39 87 85 58 22]
 [70 59 42 24 54]]


In [22]:
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [23]:
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [24]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [26]:
c = np.random.randint(10,90,(5,5))
print(c)

[[28 19 77 89 28]
 [87 17 30 76 17]
 [68 28 79 73 58]
 [28 48 85 13 85]
 [55 33 84 87 58]]


In [27]:
# array dimension
print(c.shape)

(5, 5)


In [28]:
# number of dimensions
print(c.ndim)

2


In [29]:
# number of elements in array
print(c.size)

25


In [30]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [31]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [32]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [33]:
print(a)
print(b)

[[0 0 9]
 [2 4 3]
 [6 7 4]]
[[13 18 16]
 [12 10 19]
 [14 14 19]]


In [34]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[13 18 25]
 [14 14 22]
 [20 21 23]]
[[-13 -18  -7]
 [-10  -6 -16]
 [ -8  -7 -15]]
[[  0   0 144]
 [ 24  40  57]
 [ 84  98  76]]
[[0.         0.         0.5625    ]
 [0.16666667 0.4        0.15789474]
 [0.42857143 0.5        0.21052632]]


In [35]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [36]:
print(a)
print(b)

[[5 3 3]
 [6 7 3]
 [2 2 6]]
[[10 18 14]
 [12 14 19]
 [18 13 18]]


In [37]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 21 17]
 [18 21 22]
 [20 15 24]]
[[ -5 -15 -11]
 [ -6  -7 -16]
 [-16 -11 -12]]
[[ 50  54  42]
 [ 72  98  57]
 [ 36  26 108]]
[[0.5        0.16666667 0.21428571]
 [0.5        0.5        0.15789474]
 [0.11111111 0.15384615 0.33333333]]


Array Maniputation

In [39]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 7 9]
 [8 2 1]]
(2, 3)


In [41]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 8]
 [7 2]
 [9 1]]
(3, 2)


In [42]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 4 4]
 [5 6 0]]
(2, 3)


In [43]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[2 5]
 [4 6]
 [4 0]]
(3, 2)


In [45]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 1 7]
 [4 5 5]]
(2, 3)


In [46]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 1]
 [7 4]
 [5 5]]
(3, 2)
